### ISSUE TITLE
UnicodeDecodeError when loading dictionaries

### ISSUE THREAD

**Issue by mbrown1413** [ITNG/yurika#34]
ERROR    [celery.app.trace] Task mortar.tasks.sync_dictionaries[2dfc9f8a-0605-4380-b742-bd339461e55b] raised unexpected: UnicodeDecodeError('utf-8', b'+)\nsorbitol-6-phosphate 2-dehydrogenase\n15-hydroxyprostaglandin dehydrogenase (NAD+)\nD-pinitol dehydrogenase\nsequoyitol dehydrogenase\nperillyl-alcohol dehydrogenase\n3\xce\xb2-hydroxy-\xce\x945-steroid dehydrogenase\n11\xce\xb2-hydroxysteroid dehydrogenase\n16\xce\xb1-hydroxysteroid dehydrogenase\nestradiol 17\xce\xb1-dehydrogenase\n20\xce\xb1-hydroxysteroid dehydrogenase\n21-hydroxysteroid dehydrogenase (NAD+)\n21-hydroxysteroid dehydrogenase (NADP+)\n3\xce\xb1-hydroxy-5\xce\xb2-androstane-17-one 3\xce\xb1-dehydrogenase\nsepiapterin reductase (L-erythro-7,8-dihydrobiopterin forming)\nureidoglycolate dehydrogenase\nglycerol 2-dehydrogenase (NADP+)\n3-hydroxybutyryl-CoA dehydrogenase\n7\xce\xb1-hydroxysteroid dehydrogenase\ndihydrobunolol dehydrogenase\nerythrulose reductase\ncyclopentanol dehydrogenase\nhexadecanol dehydrogenase\n2-alkyn-1-ol dehydrogenase\nhydroxycyclohexanecarboxylate dehydrogenase\nhydroxymalonate dehydrogenase\n2-dehydropantolactone reductase (Re-specific)\n2-dehydropantoate 2-reductase\n3\xce\xb2-hydroxy-4\xce\xb1-carboxy-sterol 3-dehydrogenase (decarboxylating)\n2-oxoadipate reductase\nL-rhamnose 1-dehydrogenase\ncyclohexane-1,2-diol dehydrogenase\nD-xylose 1-dehydrogenase\n12\xce\xb1-hydroxysteroid dehydrogenase\nglycerol-3-phosphate 1-dehydrogenase (NADP+)\n3-hydroxy-2-methylbutyryl-CoA dehydrogenase\nD-xylose 1-dehydrogenase (NADP+)\ncholest-5-ene-3\xce\xb2,7\xce\xb1-diol 3\xce\xb2-dehydrogenase\ngeraniol dehydrogenase\ncarbonyl reductase (NADPH)\nL-glycol dehydrogenase\ndTDP-galactose 6-dehydrogenase\nGDP-4-dehydro-D-rhamnose reductase\nprostaglandin-F synthase\nprostaglandin-E2 9-reductase\nindole-3-acetaldehyde reductase (NADH)\nindole-3-acetaldehyde reductase (NADPH)\nlong-chain-alcohol dehydrogenase\n5-amino-6-(5-phosphoribosylamino)uracil reductase\nconiferyl-alcohol dehydrogenase\ncinnamyl-alcohol dehydrogenase\n15-hydroxyprostaglandin-D dehydrogenase (NADP+)\n15-hydroxyprostaglandin dehydrogenase (NADP+)\n(+)-borneol dehydrogenase\n(S)-usnate reductase\naldose-6-phosphate reductase (NADPH)\n7\xce\xb2-hydroxysteroid dehydrogenase (NADP+)\n1,3-propanediol dehydrogenase\nuronate dehydrogenase\nIMP dehydrogenase\ntropinone reductase I\n(\xe2', 2047, 2048, 'unexpected end of data')
    Traceback (most recent call last):
    File "/opt/yurika/.venv/lib64/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
        R = retval = fun(*args, **kwargs)
    File "/opt/yurika/.venv/lib64/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
        return self.run(*args, **kwargs)
    File "/opt/yurika/mortar/tasks.py", line 96, in sync_dictionaries
        utils.update_dictionaries()
    File "/opt/yurika/mortar/utils.py", line 151, in update_dictionaries
        buff = dictfile.read(2048).decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 2047: unexpected end of data

**Comment by mbrown1413** [comment]
This was a fun one! ^__^ Here's what happened:

We were reading files in 2048-byte chunks, then decoding the bytes to unicode. Seems sensible not to read the whole thing in at once. But what happens if a chunk boundary is in the middle of a multi-byte unicode character? Well that seems pretty rare, but it happened in one of our dictionaries! One particular chunk would always fail to decode because it expected another byte that wasn't there to finish the unicode character. That's also why the error always says at "position 2047", at the end of the chunk.
